{{- if .Values.userService.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.userService.name }}-hpa
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.userService.name }}
    environment: {{ .Values.global.env }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.userService.name }}
  minReplicas: {{ .Values.userService.hpa.minReplicas }}
  # Hard cap at 2 — cluster has 10–11 GB usable workload RAM
  maxReplicas: {{ .Values.userService.hpa.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.userService.hpa.targetCPUUtilizationPercentage }}
{{- end }}
