{{- if .Values.rabbitmq.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.rabbitmq.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.rabbitmq.name }}
    app.kubernetes.io/part-of: itsm-app
    environment: {{ .Values.global.env }}
spec:
  serviceName: {{ .Values.rabbitmq.name }}
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.rabbitmq.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.rabbitmq.name }}
        environment: {{ .Values.global.env }}
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 999   # rabbitmq user in official image
        fsGroup: 999
      containers:
        - name: rabbitmq
          image: {{ .Values.rabbitmq.image }}
          imagePullPolicy: IfNotPresent
          ports:
            - name: amqp
              containerPort: {{ .Values.rabbitmq.port }}
            - name: management
              containerPort: {{ .Values.rabbitmq.managementPort }}
          env:
            - name: RABBITMQ_DEFAULT_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.rabbitmq.secretName }}
                  key: rabbitmq-user
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.rabbitmq.secretName }}
                  key: rabbitmq-password
          resources:
            requests:
              cpu: {{ .Values.rabbitmq.resources.requests.cpu }}
              memory: {{ .Values.rabbitmq.resources.requests.memory }}
            limits:
              cpu: {{ .Values.rabbitmq.resources.limits.cpu }}
              memory: {{ .Values.rabbitmq.resources.limits.memory }}
          readinessProbe:
            exec:
              command: ["rabbitmq-diagnostics", "check_port_connectivity"]
            initialDelaySeconds: 20
            periodSeconds: 15
            timeoutSeconds: 10
          livenessProbe:
            exec:
              command: ["rabbitmq-diagnostics", "status"]
            initialDelaySeconds: 40
            periodSeconds: 30
            timeoutSeconds: 15
          volumeMounts:
            - name: rabbitmq-data
              mountPath: /var/lib/rabbitmq
  volumeClaimTemplates:
    - metadata:
        name: rabbitmq-data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: {{ .Values.rabbitmq.persistence.storageClass }}
        resources:
          requests:
            storage: {{ .Values.rabbitmq.persistence.size }}
{{- end }}
