fullnameOverride: "prometheus"

alertmanager:
  enabled: false
prometheus-pushgateway:
  enabled: false
prometheus-node-exporter:
  enabled: false
kube-state-metrics:
  enabled: false

server:
  retention: "6h"
  persistentVolume:
    enabled: false
  resources:
    requests:
      cpu: 150m
      memory: 256Mi
    limits:
      cpu: 400m
      memory: 512Mi
