{{- if .Values.incidentService.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.incidentService.name }}-hpa
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.incidentService.name }}
    environment: {{ .Values.global.env }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.incidentService.name }}
  minReplicas: {{ .Values.incidentService.hpa.minReplicas }}
  maxReplicas: {{ .Values.incidentService.hpa.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.incidentService.hpa.targetCPUUtilizationPercentage }}
{{- end }}
