{{- if .Values.redis.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.redis.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.redis.name }}
    app.kubernetes.io/part-of: itsm-app
    environment: {{ .Values.global.env }}
spec:
  serviceName: {{ .Values.redis.name }}
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.redis.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.redis.name }}
        environment: {{ .Values.global.env }}
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 999   # redis user in official image
        fsGroup: 999
      containers:
        - name: redis
          image: {{ .Values.redis.image }}
          imagePullPolicy: IfNotPresent
          command:
            - redis-server
            - --appendonly
            - "yes"
            - --appendfsync
            - everysec
          ports:
            - name: redis
              containerPort: {{ .Values.redis.port }}
          resources:
            requests:
              cpu: {{ .Values.redis.resources.requests.cpu }}
              memory: {{ .Values.redis.resources.requests.memory }}
            limits:
              cpu: {{ .Values.redis.resources.limits.cpu }}
              memory: {{ .Values.redis.resources.limits.memory }}
          readinessProbe:
            exec:
              command: ["redis-cli", "ping"]
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            exec:
              command: ["redis-cli", "ping"]
            initialDelaySeconds: 15
            periodSeconds: 20
          volumeMounts:
            - name: redis-data
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: redis-data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: {{ .Values.redis.persistence.storageClass }}
        resources:
          requests:
            storage: {{ .Values.redis.persistence.size }}
{{- end }}
